### PR TITLE
Proxy and cloudflare - disable

### PR DESCRIPTION
**Pull request by longstone**
refering to https://github.com/baminteractive/express-ipfilter/issues/15

no its possible to disable both with settings, it's not disabled per default to not break code, in my opinion this is a task the repo owner has to decide (or solve it through versioning).

however, would be great if someone can review the code, because my js isn't really solid.

### CODE REVIEW

**Comment by ryanbillingsley** [comment]
@longstone First, thank you for the pull request!  With your comment, are you saying here:

> in my opinion this is a task the repo owner has to decide

That you believe it is my decision on whether they are on by default or not?  I just want to make sure I understand your concerns correctly.

**Comment by longstone** [comment]
@ryanbillingsley Yes.
Well, 'break code' is the wrong terminology. In my opinion they should be disabled by default.

**Comment by ryanbillingsley** [comment]
@longstone I would agree with that.  I think if you need access to that feature (cloud flare, et al) then you should explicitly opt into it.  If you have the time, go ahead and change the defaults to false.  Thanks again for the contribution :+1:

**Comment by longstone** [comment]
@ryanbillingsley you're welcome. Now it's disabled by default.

**Pull request merged**
