### PR TITLE
Pass the getClientIp function to the custom detectIp function

### PR DESCRIPTION
**Pull request by alaycock**
My intention is to allow custom detectIp functions to fallback or build on the default implementation if they need to.

I included my yarn.lock, if you prefer not to use it, I can pull it out.

### CODE REVIEW

**Comment by ryanbillingsley** [comment]
@alaycock what kind of use case were you looking at for this?

**Comment by alaycock** [comment]
My use case is that I want to detect the IP through the application headers if the header exists. But there's a chance the header won't exist, and if it doesn't, I'd like to fall back to the default implementation.

After giving it a bit more thought, I realized it probably makes more sense to export `getClientIp` from the package than to include it in the function call to `detectIp`.

**Comment by pdefreitas** [comment]
This is very useful for scenarios where we're behind a reverse proxy.
Example:
http://expressjs.com/en/guide/behind-proxies.html

**Comment by alaycock** [comment]
Thanks for commenting on this @pdefreitas, my solution probably isn't the best option. A better solution might be to export the `getClientIp` function, rather than passing it in as a function argument. Perhaps a project contributor could chime in, but I'm going to close this PR in favour of exporting it.

**Pull request closed without merging**
