### PR TITLE
Ability to pass callback function for IP addresses.

### PR DESCRIPTION
**Pull request by armiiller**
1) Adds the ability to pass ips by funtion so that we can dynamically retrieve addresses. 2) Updates the README to add examples of passing a funtion. 3) Adds tests to test the ips by function. 4) Updates the CONTRIBUTING with the missing grunt step.

This enables a "dynamicness" to the middleware so we can change blocked ips on the fly.

### CODE REVIEW

**Comment by armiiller** [comment]
Hi @ryanbillingsley,

Any eta on when this might get pulled in? We are trying to get some code pushed, and the updated package would make this possible.

Thanks,
Austin

**Comment by ryanbillingsley** [comment]
@armiiller I will do my best to review it today

**Comment by armiiller** [comment]
@ryanbillingsley - Hey Ryan - I made the requested changes. You can see them here https://github.com/baminteractive/express-ipfilter/pull/55/commits/b6834051f54b312ab44167561a3c7614614ef633

**Comment by ryanbillingsley** [comment]
@armiiller changes are merged in, thanks again for the work 👍

**Comment by armiiller** [comment]
Absolutely! Thanks for the quick responses!

I think you can also close these two issues:
https://github.com/baminteractive/express-ipfilter/issues/51
https://github.com/baminteractive/express-ipfilter/issues/47

**Pull request merged**
