### PR TITLE
Fixed issue with IPv6 localhost address `::1`

### PR DESCRIPTION
**Pull request by LukevdPalen**

### CODE REVIEW

**Comment by ryanbillingsley** [comment]
@LukevdPalen could you provide a test case around this?

**Comment by muddydixon** [comment]
hi !
Will you merge this p-r?
I wanna treat ipv6.

**Comment by ryanbillingsley** [comment]
I will take a look at this today hopefully

**Comment by ryanbillingsley** [comment]
Merged these changes in with some others

**Comment by muddydixon** [comment]
:clap:

**Pull request closed without merging**
